pipeline {

  agent any
  environment {
    //adding a comment for the commit test
    DEPLOY_CREDS = credentials('deploy-anypoint-user')
    MULE_VERSION = '4.2.1'
    BG = "ABC"
    WORKER = "Micro"
  }
  stages {
	  
stage('CD') {
      steps {
            bat 'cd hello-cicd'
	    echo %cd%
      }
    }
	
    stage('Build') {
      steps {
	    echo %cd%
            bat 'mvn -B -U -e -V clean -DskipTests package'
      }
    }

    stage('Test') {
      steps {
          bat "mvn test"
      }
    }

     stage('CloudHub Deployment') {
      environment {
        ENVIRONMENT = 'Sandbox'
        APP_NAME = 'hello-cicd-dev'
      }
      steps {
            bat 'mvn -U -V -e -B -DskipTests deploy -DmuleDeploy -Dmule.version="%MULE_VERSION%" -Danypoint.username="%DEPLOY_CREDS_USR%" -Danypoint.password="%DEPLOY_CREDS_PSW%" -Dcloudhub.app="%APP_NAME%" -Dcloudhub.environment="%ENVIRONMENT%" -Dcloudhub.bg="%BG%" -Dcloudhub.worker="%WORKER%"'
      }
    }
  }
}
